[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';
      script-src 'self' https://connect.facebook.net https://www.googletagmanager.com;
      img-src 'self' data: https://www.facebook.com https://res.cloudinary.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      frame-src 'self' https://www.facebook.com;"
